### PR TITLE
Add UI test target

### LINKED ISSUE #16: Determine Test Automation approach

### PR DESCRIPTION
**Pull request by stavares843**
**What this PR does**:
Add UI test target to add automated tests 

**Which issue(s) this PR fixes**:
https://github.com/FightPandemics/FightPandemics-iOS/issues/16

### CODE REVIEW

**Comment by haidalinda** [comment]
@stavares843 i'm getting a couple errors when running tests

ui-test-setup-errors

`Method does not override any method from its superclass`

**Comment by stavares843** [comment]
compiling doesnt show the error

Screenshot 2020-05-10 at 17 37 18

when running the tests also doesnt show the error

Screenshot 2020-05-10 at 17 38 33


can you try clean and try to compile again?

**Comment by haidalinda** [comment]
@stavares843 compiling doesnt show correct - it shows up when tests are run. if you hit `Ctrl+U`, Xcode will run tests

**Review by haidalinda — CHANGES_REQUESTED** [review]
see convo

**Comment by stavares843** [comment]
yes when running the tests is also working fine here

Screenshot 2020-05-10 at 17 38 33

will take a look

**Review by haidalinda — APPROVED** [review]

**Comment by haidalinda** [comment]
resolved - my compilation issues is because i'm running Xcode 11.1 and those `override`s are for an Xcode 11.4 context

**Pull request merged**
