### PR TITLE
offer or request help page

### LINKED ISSUE #59: Post creation - offer or request help
**AS** a user,
**Given** that I am on the "create a post" page 
**When** I tap on "make a selection" dropdown menu
**Then** a pop up appears with 2 options: Offering; Requesting 
**When** I tap on Offering (same thing applies when tapping on Requesting)
**Then** the UI change
**And then** I can tap on Confirm

**Design**
Capture d’écran 2020-05-14 à 16 32 43
Capture d’écran 2020-05-14 à 16 33 05

**Acceptance criteria** 
Tapping on "make a selection" opens the pop up
The UI change when the user tap on either Offering or Requesting 
The confirm button should be disabled if "offering" or "requesting" button is not selected

### PR DESCRIPTION
**Pull request by ethanswift**
**What this PR does**:
This is offer or request selection page
Unfortunately the image didn't get uploaded. I'll try to upload it in the comments, later. 

### Checklist

[x] Compiler warnings resolved
[x] Linter warnings resolved
[x] User-facing strings in Localizable.strings file
[x] Unused code, print statements, and comments removed

**Which issue(s) this PR fixes**:

Resolves #

**Special notes for reviewers**:

**Additional comments**:

### CODE REVIEW

**Review by stavares843 — CHANGES_REQUESTED** [review]
doesn't compile

> error: Build input file cannot be found: '/Users/stavares/OfferReq.swift' (in target 'FightPandemics' from project 'FightPandemics')

**Comment by ethanswift** [comment]
> doesn't compile
> 
> > error: Build input file cannot be found: '/Users/stavares/OfferReq.swift' (in target 'FightPandemics' from project 'FightPandemics')

It's running on my device

**Comment by stavares843** [comment]
going to FightPandemics.xcodeproj/project.pbxproj seems the file was added but seems theres no OfferReq.swift itself added on the project

**Comment by ethanswift** [comment]
> going to FightPandemics.xcodeproj/project.pbxproj seems the file was added but seems theres no OfferReq.swift itself added on the project

That's right!!!! the file hasn't been added! what should I do now? I pushed again but the file seems to not uploaded!!

**Comment by ethanswift** [comment]
> going to FightPandemics.xcodeproj/project.pbxproj seems the file was added but seems theres no OfferReq.swift itself added on the project

The file is not appearing in file changes!! but it's already in my project and I pushed again it should have been uploaded

**Comment by stavares843** [comment]
the file appears on the sourcetree (or any other program you use for source control?

Screenshot 2020-05-15 at 22 15 15

or going to git status?

maybe try to remove the file from local and add it again and push it again could be some bug on git or on xcode

**Comment by stavares843** [comment]
strange is not being added

whats the path that appears here going to that file?

Screenshot 2020-05-15 at 22 29 10

**Comment by ethanswift** [comment]
> strange is not being added
> 
> whats the path that appears here going to that file?
> 
> Screenshot 2020-05-15 at 22 29 10

How can I delete this PR and make a new one?

**Comment by ethanswift** [comment]
Is there any way to delete this PR and make a new one ?

**Pull request closed without merging**
