### PR TITLE
swiftformat

### PR DESCRIPTION
**Pull request by stavares843**
**What this PR does**:

this adds swiftformat to the project, by adding the swiftformat pod and by running the swifformat script on the Build phases as well

more info here

https://github.com/nicklockwood/SwiftFormat

example

Screenshot 2020-05-18 at 18 37 45

### CODE REVIEW

**Comment by ethanswift** [comment]
It removes any unnecessary space, removes self, ... interesting !!

**Review by haidalinda — CHANGES_REQUESTED** [review]
if folks running the project will need to install `swiftformat` on their machines - can you add a step to the `Getting Started` section of the `README` to indicate how to do so?

**Comment by haidalinda** [comment]
> if folks running the project will need to install `swiftformat` on their machines - can you add a step to the `Getting Started` section of the `README` to indicate how to do so?

seems unnecessary - disregard !

**Comment by haidalinda** [comment]
im good with this @stavares843 👍  i think its going to be easier to avoid conflicts if we merge the Tab Bar work first then this

**Comment by haidalinda** [comment]
tab bar was closed - good to merge. thanks for improving the quality of the codebase @stavares843 !

**Review by haidalinda — APPROVED** [review]

**Review by haidalinda — CHANGES_REQUESTED** [review]
let's also add SwiftFormat to our credits!

https://github.com/FightPandemics/FightPandemics-iOS/blob/develop/FightPandemics/Resources/OpenSourceCredits.json

https://github.com/FightPandemics/FightPandemics-iOS/blob/develop/CREDITS.md

**Comment by stavares843** [comment]
added swiftformat to the credits here

https://github.com/FightPandemics/FightPandemics-iOS/pull/113

**Review by haidalinda — APPROVED** [review]

**Review by ethanswift — APPROVED** [review]

**Pull request merged**
